# ============================================================================
# Makefile – STM32F446RET6 Air Purifier
#
# Requires arm-none-eabi-gcc (GNU Arm Embedded Toolchain).
# Assumes the STM32CubeF4 HAL source is available under the path specified
# by CUBE_ROOT (default: ${HOME}/STM32Cube/Repository/STM32Cube_FW_F4_V1.28.0).
# Override via: make CUBE_ROOT=/your/path
# ============================================================================

TARGET      = air-purifier-stm32
BUILD_DIR   = build

# --------------------------------------------------------------------------
# Toolchain
# --------------------------------------------------------------------------
PREFIX   = arm-none-eabi-
CC       = $(PREFIX)gcc
AS       = $(PREFIX)gcc -x assembler-with-cpp
CP       = $(PREFIX)objcopy
SZ       = $(PREFIX)size
HEX      = $(CP) -O ihex
BIN      = $(CP) -O binary -S

# --------------------------------------------------------------------------
# STM32CubeF4 HAL root (override on the command line if needed)
# --------------------------------------------------------------------------
CUBE_ROOT ?= $(HOME)/STM32Cube/Repository/STM32Cube_FW_F4_V1.28.0

HAL_ROOT  = $(CUBE_ROOT)/Drivers/STM32F4xx_HAL_Driver
CMSIS_ROOT = $(CUBE_ROOT)/Drivers/CMSIS

# --------------------------------------------------------------------------
# CPU / FPU flags
# --------------------------------------------------------------------------
CPU     = -mcpu=cortex-m4
FPU     = -mfpu=fpv4-sp-d16
FLOAT   = -mfloat-abi=hard
MCU     = $(CPU) -mthumb $(FPU) $(FLOAT)

# --------------------------------------------------------------------------
# C compiler flags
# --------------------------------------------------------------------------
CFLAGS  = $(MCU)
CFLAGS += -DUSE_HAL_DRIVER
CFLAGS += -DSTM32F446xx
CFLAGS += -IInc
CFLAGS += -I$(HAL_ROOT)/Inc
CFLAGS += -I$(HAL_ROOT)/Inc/Legacy
CFLAGS += -I$(CMSIS_ROOT)/Device/ST/STM32F4xx/Include
CFLAGS += -I$(CMSIS_ROOT)/Include
CFLAGS += -Og -Wall -Wextra -fdata-sections -ffunction-sections
CFLAGS += -MMD -MP

# --------------------------------------------------------------------------
# Assembler flags
# --------------------------------------------------------------------------
ASFLAGS = $(MCU) -Wall -fdata-sections -ffunction-sections

# --------------------------------------------------------------------------
# Linker flags
# --------------------------------------------------------------------------
LDSCRIPT = STM32F446RETx/STM32F446RETx_FLASH.ld
LIBS     = -lc -lm -lnosys
LDFLAGS  = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBS)
LDFLAGS += -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref
LDFLAGS += -Wl,--gc-sections

# --------------------------------------------------------------------------
# Source files
# --------------------------------------------------------------------------
C_SOURCES = \
  Src/main.c          \
  Src/dht22.c         \
  Src/aqi.c           \
  Src/oled.c          \
  Src/hepa_fan.c      \
  Src/stm32f4xx_it.c  \
  $(HAL_ROOT)/Src/stm32f4xx_hal.c                \
  $(HAL_ROOT)/Src/stm32f4xx_hal_rcc.c            \
  $(HAL_ROOT)/Src/stm32f4xx_hal_rcc_ex.c         \
  $(HAL_ROOT)/Src/stm32f4xx_hal_gpio.c           \
  $(HAL_ROOT)/Src/stm32f4xx_hal_dma.c            \
  $(HAL_ROOT)/Src/stm32f4xx_hal_dma_ex.c         \
  $(HAL_ROOT)/Src/stm32f4xx_hal_cortex.c         \
  $(HAL_ROOT)/Src/stm32f4xx_hal_flash.c          \
  $(HAL_ROOT)/Src/stm32f4xx_hal_flash_ex.c       \
  $(HAL_ROOT)/Src/stm32f4xx_hal_pwr.c            \
  $(HAL_ROOT)/Src/stm32f4xx_hal_pwr_ex.c         \
  $(HAL_ROOT)/Src/stm32f4xx_hal_i2c.c            \
  $(HAL_ROOT)/Src/stm32f4xx_hal_i2c_ex.c         \
  $(HAL_ROOT)/Src/stm32f4xx_hal_uart.c           \
  $(HAL_ROOT)/Src/stm32f4xx_hal_tim.c            \
  $(HAL_ROOT)/Src/stm32f4xx_hal_tim_ex.c

ASM_SOURCES = \
  STM32F446RETx/startup_stm32f446xx.s

# --------------------------------------------------------------------------
# Object files
# --------------------------------------------------------------------------
OBJECTS  = $(addprefix $(BUILD_DIR)/, $(notdir $(C_SOURCES:.c=.o)))
OBJECTS += $(addprefix $(BUILD_DIR)/, $(notdir $(ASM_SOURCES:.s=.o)))

# Dependency files (auto-generated by -MMD -MP)
-include $(OBJECTS:.o=.d)

# VPATH: let make find sources in any subdirectory
vpath %.c $(sort $(dir $(C_SOURCES)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

# --------------------------------------------------------------------------
# Targets
# --------------------------------------------------------------------------
.PHONY: all clean flash

all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex \
     $(BUILD_DIR)/$(TARGET).bin
	$(SZ) $<

# ELF
$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS)
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@

# HEX / BIN
$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf
	$(BIN) $< $@

# Compile C sources
$(BUILD_DIR)/%.o: %.c | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

# Assemble startup file
$(BUILD_DIR)/%.o: %.s | $(BUILD_DIR)
	$(AS) -c $(ASFLAGS) $< -o $@

$(BUILD_DIR):
	mkdir -p $@

# --------------------------------------------------------------------------
# Flash via OpenOCD (STLink)
# --------------------------------------------------------------------------
flash: $(BUILD_DIR)/$(TARGET).bin
	openocd -f interface/stlink.cfg -f target/stm32f4x.cfg \
	  -c "program $(BUILD_DIR)/$(TARGET).bin 0x08000000 verify reset exit"

# --------------------------------------------------------------------------
# Clean
# --------------------------------------------------------------------------
clean:
	rm -rf $(BUILD_DIR)
